// export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
// export const TOGGLE_SIGNIN = "TOGGLE_SIGNIN";
// export const TOGGLE_EMAIL_LOGIN = "TOGGLE_EMAIL_LOGIN";
// export const TOGGLE_OTP_VERIFY = "TOGGLE_OTP_VERIFY";
// export const TOGGLE_WAIT_OTP = "TOGGLE_WAIT_OTP";
// export const TOGGLE_EMAIL_ERROR = "TOGGLE_EMAIL_ERROR";

// export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
// export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
// export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";